#nullable disable

using NB21_logger.Properties;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace NB21_logger;

partial class NB21Logger
{
  private IContainer components = null;
  private TabControl tabControl1;
  private TabPage tabPage_Home;
  private TabPage tabPage_Settings;
  private ImageList imageList1;
  private PictureBox pictureBox_statusImage;
  private Label ui_conn_status;
  private Label label1;
  private TextBox ui_settings_pilot_name;
  private TextBox ui_settings_pilot_id;
  private TextBox ui_settings_igc_path;
  private Label label2;
  private Button button1;
  private Label label3;
  private Label ui_local_date;
  private Label ui_aircraft_label;
  private Label ui_pilot_label;
  private Label ui_local_time;
  private Label ui_aircraft;
  private Label ui_pilot;
  private Label ui_auto_start_label1;
  private CheckBox ui_auto_start_checkbox;
  private Label ui_task;
  private Label ui_recording_time;
  private Label ui_sim_rate;
  private Label ui_simtime_label;
  private Button view_tracklogs_button;
  private Label ui_message_bar;
  private PictureBox ui_file_icon;
  private LinkLabel ui_min_max;
  private LinkLabel ui_web_urls;
  private Button ui_task_button;
  private Label pln_drop_outline;

  protected override void Dispose(bool disposing)
  {
    if (disposing)
    {
      this.DetachFromHostForm();
      this.PerformShutdownTasks();
      if (this.components != null)
        this.components.Dispose();
    }
    base.Dispose(disposing);
  }

  private void InitializeComponent()
  {
    this.components = (IContainer) new System.ComponentModel.Container();
    ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof (NB21Logger));
    this.tabControl1 = new TabControl();
    this.tabPage_Home = new TabPage();
    this.ui_task_button = new Button();
    this.ui_file_icon = new PictureBox();
    this.ui_min_max = new LinkLabel();
    this.ui_message_bar = new Label();
    this.view_tracklogs_button = new Button();
    this.ui_simtime_label = new Label();
    this.ui_recording_time = new Label();
    this.ui_sim_rate = new Label();
    this.ui_task = new Label();
    this.ui_aircraft = new Label();
    this.ui_pilot = new Label();
    this.ui_aircraft_label = new Label();
    this.ui_pilot_label = new Label();
    this.ui_local_time = new Label();
    this.ui_local_date = new Label();
    this.ui_conn_status = new Label();
    this.pictureBox_statusImage = new PictureBox();
    this.pln_drop_outline = new Label();
    this.tabPage_Settings = new TabPage();
    this.ui_web_urls = new LinkLabel();
    this.label3 = new Label();
    this.button1 = new Button();
    this.ui_settings_igc_path = new TextBox();
    this.label2 = new Label();
    this.ui_settings_pilot_id = new TextBox();
    this.label1 = new Label();
    this.ui_settings_pilot_name = new TextBox();
    this.ui_auto_start_label1 = new Label();
    this.ui_auto_start_checkbox = new CheckBox();
    this.imageList1 = new ImageList(this.components);
    this.tabControl1.SuspendLayout();
    this.tabPage_Home.SuspendLayout();
    ((ISupportInitialize) this.ui_file_icon).BeginInit();
    ((ISupportInitialize) this.pictureBox_statusImage).BeginInit();
    this.tabPage_Settings.SuspendLayout();
    this.SuspendLayout();
    this.tabControl1.Alignment = TabAlignment.Left;
    this.tabControl1.Anchor = AnchorStyles.Top | AnchorStyles.Right;
    this.tabControl1.Controls.Add((Control) this.tabPage_Home);
    this.tabControl1.Controls.Add((Control) this.tabPage_Settings);
    this.tabControl1.ImageList = this.imageList1;
    this.tabControl1.ItemSize = new Size(115, 60);
    this.tabControl1.Location = new Point(2, 0);
    this.tabControl1.Margin = new Padding(0);
    this.tabControl1.Multiline = true;
    this.tabControl1.Name = "tabControl1";
    this.tabControl1.Padding = new Point(0, 0);
    this.tabControl1.SelectedIndex = 0;
    this.tabControl1.Size = new Size(592, 244);
    this.tabControl1.SizeMode = TabSizeMode.Fixed;
    this.tabControl1.TabIndex = 1;
    this.tabControl1.Click += new EventHandler(this.ui_tab_click);
    this.tabPage_Home.AllowDrop = true;
    this.tabPage_Home.BackColor = System.Drawing.Color.LightCyan;
    this.tabPage_Home.Controls.Add((Control) this.ui_task_button);
    this.tabPage_Home.Controls.Add((Control) this.ui_file_icon);
    this.tabPage_Home.Controls.Add((Control) this.ui_min_max);
    this.tabPage_Home.Controls.Add((Control) this.ui_message_bar);
    this.tabPage_Home.Controls.Add((Control) this.view_tracklogs_button);
    this.tabPage_Home.Controls.Add((Control) this.ui_simtime_label);
    this.tabPage_Home.Controls.Add((Control) this.ui_recording_time);
    this.tabPage_Home.Controls.Add((Control) this.ui_sim_rate);
    this.tabPage_Home.Controls.Add((Control) this.ui_task);
    this.tabPage_Home.Controls.Add((Control) this.ui_aircraft);
    this.tabPage_Home.Controls.Add((Control) this.ui_pilot);
    this.tabPage_Home.Controls.Add((Control) this.ui_aircraft_label);
    this.tabPage_Home.Controls.Add((Control) this.ui_pilot_label);
    this.tabPage_Home.Controls.Add((Control) this.ui_local_time);
    this.tabPage_Home.Controls.Add((Control) this.ui_local_date);
    this.tabPage_Home.Controls.Add((Control) this.ui_conn_status);
    this.tabPage_Home.Controls.Add((Control) this.pictureBox_statusImage);
    this.tabPage_Home.Controls.Add((Control) this.pln_drop_outline);
    this.tabPage_Home.ImageIndex = 0;
    this.tabPage_Home.Location = new Point(64 /*0x40*/, 4);
    this.tabPage_Home.Margin = new Padding(3, 2, 3, 2);
    this.tabPage_Home.Name = "tabPage_Home";
    this.tabPage_Home.Padding = new Padding(3, 2, 3, 2);
    this.tabPage_Home.Size = new Size(524, 236);
    this.tabPage_Home.TabIndex = 0;
    this.tabPage_Home.DragOver += new DragEventHandler(this.ui_home_dragover);
    this.tabPage_Home.Enter += new EventHandler(this.ui_home_select);
    this.ui_task_button.AllowDrop = true;
    this.ui_task_button.Font = new Font("Segoe UI", 12f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.ui_task_button.Location = new Point(22, 148);
    this.ui_task_button.Name = "ui_task_button";
    this.ui_task_button.Size = new Size(97, 30);
    this.ui_task_button.TabIndex = 17;
    this.ui_task_button.Text = "Task:";
    this.ui_task_button.TextAlign = ContentAlignment.MiddleRight;
    this.ui_task_button.UseVisualStyleBackColor = true;
    this.ui_task_button.Click += new EventHandler(this.ui_task_click);
    this.ui_task_button.DragDrop += new DragEventHandler(this.ui_task_DragDrop);
    this.ui_task_button.DragEnter += new DragEventHandler(this.ui_task_DragEnter);
    this.ui_file_icon.Image = (Image) Resources.file_icon;
    this.ui_file_icon.Location = new Point(476, 174);
    this.ui_file_icon.Name = "ui_file_icon";
    this.ui_file_icon.Size = new Size(38, 57);
    this.ui_file_icon.SizeMode = PictureBoxSizeMode.StretchImage;
    this.ui_file_icon.TabIndex = 16;
    this.ui_file_icon.TabStop = false;
    this.ui_file_icon.MouseDown += new MouseEventHandler(this.ui_file_drag);
    this.ui_min_max.AutoSize = true;
    this.ui_min_max.Font = new Font("Segoe UI", 9f);
    this.ui_min_max.Location = new Point(452, 12);
    this.ui_min_max.Name = "ui_min_max";
    this.ui_min_max.Size = new Size(60, 15);
    this.ui_min_max.TabIndex = 15;
    this.ui_min_max.TabStop = true;
    this.ui_min_max.Text = "Compact";
    this.ui_min_max.LinkClicked += new LinkLabelLinkClickedEventHandler(this.ui_min_max_LinkClicked);
    this.ui_message_bar.Font = new Font("Segoe UI", 9f, FontStyle.Bold);
    this.ui_message_bar.ForeColor = System.Drawing.Color.DarkBlue;
    this.ui_message_bar.Location = new Point(22, 205);
    this.ui_message_bar.Margin = new Padding(3, 0, 0, 0);
    this.ui_message_bar.Name = "ui_message_bar";
    this.ui_message_bar.Size = new Size(468, 28);
    this.ui_message_bar.TabIndex = 14;
    this.ui_message_bar.Text = "Message Bar";
    this.ui_message_bar.TextAlign = ContentAlignment.MiddleCenter;
    this.view_tracklogs_button.Location = new Point(392, 174);
    this.view_tracklogs_button.Name = "view_tracklogs_button";
    this.view_tracklogs_button.Size = new Size(78, 57);
    this.view_tracklogs_button.TabIndex = 13;
    this.view_tracklogs_button.Text = "Tracklogs";
    this.view_tracklogs_button.UseVisualStyleBackColor = true;
    this.view_tracklogs_button.Click += new EventHandler(this.ui_view_tracklogs);
    this.ui_simtime_label.Font = new Font("Segoe UI", 12f, FontStyle.Bold);
    this.ui_simtime_label.Location = new Point(14, 96);
    this.ui_simtime_label.Name = "ui_simtime_label";
    this.ui_simtime_label.Size = new Size(102, 27);
    this.ui_simtime_label.TabIndex = 12;
    this.ui_simtime_label.Text = "Local Time:";
    this.ui_simtime_label.TextAlign = ContentAlignment.MiddleRight;
    this.ui_recording_time.AutoSize = true;
    this.ui_recording_time.BackColor = System.Drawing.Color.Transparent;
    this.ui_recording_time.Font = new Font("Lucida Console", 12f, FontStyle.Bold);
    this.ui_recording_time.Location = new Point(250, 28);
    this.ui_recording_time.MinimumSize = new Size(50, 24);
    this.ui_recording_time.Name = "ui_recording_time";
    this.ui_recording_time.Size = new Size(131, 24);
    this.ui_recording_time.TabIndex = 11;
    this.ui_recording_time.Text = "00:00:00";
    this.ui_sim_rate.BackColor = System.Drawing.Color.Transparent;
    this.ui_sim_rate.Font = new Font("Lucida Console", 14.25f, FontStyle.Bold);
    this.ui_sim_rate.Location = new Point(379, 28);
    this.ui_sim_rate.MinimumSize = new Size(10, 24);
    this.ui_sim_rate.Name = "ui_sim_rate";
    this.ui_sim_rate.Size = new Size(56, 24);
    this.ui_sim_rate.TabIndex = 10;
    this.ui_sim_rate.Text = "x16";
    this.ui_task.AllowDrop = true;
    this.ui_task.AutoEllipsis = true;
    this.ui_task.Font = new Font("Segoe UI", 14.25f);
    this.ui_task.ForeColor = SystemColors.GrayText;
    this.ui_task.Location = new Point(125, 148);
    this.ui_task.Name = "ui_task";
    this.ui_task.Size = new Size(365, 25);
    this.ui_task.TabIndex = 9;
    this.ui_task.Text = "                 PLN Drop Zone";
    this.ui_task.DragDrop += new DragEventHandler(this.ui_task_DragDrop);
    this.ui_task.DragEnter += new DragEventHandler(this.ui_task_DragEnter);
    this.ui_aircraft.AutoEllipsis = true;
    this.ui_aircraft.Font = new Font("Segoe UI", 14.25f);
    this.ui_aircraft.Location = new Point(125, 116);
    this.ui_aircraft.Name = "ui_aircraft";
    this.ui_aircraft.Size = new Size(365, 25);
    this.ui_aircraft.TabIndex = 8;
    this.ui_aircraft.Text = "??";
    this.ui_pilot.AutoSize = true;
    this.ui_pilot.Font = new Font("Segoe UI", 14.25f);
    this.ui_pilot.Location = new Point(125, 69);
    this.ui_pilot.Name = "ui_pilot";
    this.ui_pilot.Size = new Size(249, 25);
    this.ui_pilot.TabIndex = 7;
    this.ui_pilot.Text = "<Please update in Settings>";
    this.ui_aircraft_label.Font = new Font("Segoe UI", 12f, FontStyle.Bold);
    this.ui_aircraft_label.Location = new Point(14, 117);
    this.ui_aircraft_label.Name = "ui_aircraft_label";
    this.ui_aircraft_label.Size = new Size(102, 27);
    this.ui_aircraft_label.TabIndex = 5;
    this.ui_aircraft_label.Text = "Aircraft:";
    this.ui_aircraft_label.TextAlign = ContentAlignment.MiddleRight;
    this.ui_pilot_label.Font = new Font("Segoe UI", 12f, FontStyle.Bold);
    this.ui_pilot_label.Location = new Point(14, 65);
    this.ui_pilot_label.Name = "ui_pilot_label";
    this.ui_pilot_label.Size = new Size(102, 34);
    this.ui_pilot_label.TabIndex = 4;
    this.ui_pilot_label.Text = "Pilot:";
    this.ui_pilot_label.TextAlign = ContentAlignment.MiddleRight;
    this.ui_local_time.Font = new Font("Lucida Console", 18f, FontStyle.Bold);
    this.ui_local_time.Location = new Point(267, 97);
    this.ui_local_time.Name = "ui_local_time";
    this.ui_local_time.Size = new Size(160 /*0xA0*/, 23);
    this.ui_local_time.TabIndex = 3;
    this.ui_local_time.Text = "00:00:00";
    this.ui_local_date.Font = new Font("Segoe UI", 15.75f, FontStyle.Bold);
    this.ui_local_date.Location = new Point(125, 88);
    this.ui_local_date.Name = "ui_local_date";
    this.ui_local_date.Size = new Size(146, 34);
    this.ui_local_date.TabIndex = 2;
    this.ui_local_date.Text = "??";
    this.ui_conn_status.Font = new Font("Segoe UI", 14.25f, FontStyle.Bold);
    this.ui_conn_status.Location = new Point(77, 23);
    this.ui_conn_status.Margin = new Padding(3, 0, 0, 0);
    this.ui_conn_status.MinimumSize = new Size(80 /*0x50*/, 32 /*0x20*/);
    this.ui_conn_status.Name = "ui_conn_status";
    this.ui_conn_status.Size = new Size(380, 32 /*0x20*/);
    this.ui_conn_status.TabIndex = 1;
    this.ui_conn_status.Text = "MSFS Status";
    this.pictureBox_statusImage.InitialImage = (Image) null;
    this.pictureBox_statusImage.Location = new Point(25, 12);
    this.pictureBox_statusImage.Margin = new Padding(3, 2, 3, 2);
    this.pictureBox_statusImage.Name = "pictureBox_statusImage";
    this.pictureBox_statusImage.Size = new Size(50, 50);
    this.pictureBox_statusImage.SizeMode = PictureBoxSizeMode.Zoom;
    this.pictureBox_statusImage.TabIndex = 0;
    this.pictureBox_statusImage.TabStop = false;
    this.pln_drop_outline.BackColor = System.Drawing.Color.Transparent;
    this.pln_drop_outline.BorderStyle = BorderStyle.FixedSingle;
    this.pln_drop_outline.Location = new Point(19, 146);
    this.pln_drop_outline.Margin = new Padding(0);
    this.pln_drop_outline.Name = "pln_drop_outline";
    this.pln_drop_outline.Size = new Size(483, 35);
    this.pln_drop_outline.TabIndex = 18;
    this.tabPage_Settings.BackColor = System.Drawing.Color.Lavender;
    this.tabPage_Settings.Controls.Add((Control) this.ui_web_urls);
    this.tabPage_Settings.Controls.Add((Control) this.label3);
    this.tabPage_Settings.Controls.Add((Control) this.button1);
    this.tabPage_Settings.Controls.Add((Control) this.ui_settings_igc_path);
    this.tabPage_Settings.Controls.Add((Control) this.label2);
    this.tabPage_Settings.Controls.Add((Control) this.ui_settings_pilot_id);
    this.tabPage_Settings.Controls.Add((Control) this.label1);
    this.tabPage_Settings.Controls.Add((Control) this.ui_settings_pilot_name);
    this.tabPage_Settings.Controls.Add((Control) this.ui_auto_start_label1);
    this.tabPage_Settings.Controls.Add((Control) this.ui_auto_start_checkbox);
    this.tabPage_Settings.ImageIndex = 1;
    this.tabPage_Settings.Location = new Point(64 /*0x40*/, 4);
    this.tabPage_Settings.Margin = new Padding(3, 2, 3, 2);
    this.tabPage_Settings.Name = "tabPage_Settings";
    this.tabPage_Settings.Padding = new Padding(3, 2, 3, 2);
    this.tabPage_Settings.Size = new Size(524, 236);
    this.tabPage_Settings.TabIndex = 1;
    this.tabPage_Settings.Enter += new EventHandler(this.ui_settings_select);
    this.tabPage_Settings.Leave += new EventHandler(this.ui_settings_losefocus);
    this.ui_web_urls.AutoSize = true;
    this.ui_web_urls.BackColor = SystemColors.ButtonFace;
    this.ui_web_urls.Cursor = Cursors.Arrow;
    this.ui_web_urls.Location = new Point(6, 208 /*0xD0*/);
    this.ui_web_urls.Name = "ui_web_urls";
    this.ui_web_urls.Size = new Size(0, 15);
    this.ui_web_urls.TabIndex = 8;
    this.ui_web_urls.TabStop = true;
    this.ui_web_urls.LinkClicked += new LinkLabelLinkClickedEventHandler(this.ui_web_click);
    this.label3.AutoSize = true;
    this.label3.Font = new Font("Segoe UI", 14.25f, FontStyle.Bold);
    this.label3.Location = new Point(36, 56);
    this.label3.Name = "label3";
    this.label3.Size = new Size(83, 25);
    this.label3.TabIndex = 7;
    this.label3.Text = "Pilot ID:";
    this.label3.TextAlign = ContentAlignment.MiddleRight;
    this.button1.Location = new Point(135, 92);
    this.button1.Name = "button1";
    this.button1.Size = new Size(59, 30);
    this.button1.TabIndex = 6;
    this.button1.Text = "Folder...";
    this.button1.UseVisualStyleBackColor = true;
    this.button1.Click += new EventHandler(this.ui_choose_log_folder_click);
    this.ui_settings_igc_path.Enabled = false;
    this.ui_settings_igc_path.Location = new Point(6, (int) sbyte.MaxValue);
    this.ui_settings_igc_path.Name = "ui_settings_igc_path";
    this.ui_settings_igc_path.Size = new Size(469, 23);
    this.ui_settings_igc_path.TabIndex = 5;
    this.label2.AutoSize = true;
    this.label2.Font = new Font("Segoe UI", 14.25f, FontStyle.Bold);
    this.label2.Location = new Point(18, 94);
    this.label2.Name = "label2";
    this.label2.Size = new Size(102, 25);
    this.label2.TabIndex = 4;
    this.label2.Text = "Tracklogs:";
    this.label2.TextAlign = ContentAlignment.MiddleRight;
    this.ui_settings_pilot_id.Font = new Font("Segoe UI", 14.25f);
    this.ui_settings_pilot_id.Location = new Point(135, 52);
    this.ui_settings_pilot_id.Name = "ui_settings_pilot_id";
    this.ui_settings_pilot_id.Size = new Size(100, 33);
    this.ui_settings_pilot_id.TabIndex = 2;
    this.label1.AutoSize = true;
    this.label1.Font = new Font("Segoe UI", 14.25f, FontStyle.Bold);
    this.label1.Location = new Point(0, 15);
    this.label1.Name = "label1";
    this.label1.Size = new Size(115, 25);
    this.label1.TabIndex = 1;
    this.label1.Text = "Pilot Name:";
    this.label1.TextAlign = ContentAlignment.MiddleRight;
    this.ui_settings_pilot_name.Font = new Font("Segoe UI", 14.25f);
    this.ui_settings_pilot_name.Location = new Point(135, 13);
    this.ui_settings_pilot_name.Name = "ui_settings_pilot_name";
    this.ui_settings_pilot_name.Size = new Size(300, 33);
    this.ui_settings_pilot_name.TabIndex = 0;
    this.ui_auto_start_label1.AutoSize = true;
    this.ui_auto_start_label1.Font = new Font("Segoe UI", 14.25f, FontStyle.Bold);
    this.ui_auto_start_label1.Location = new Point(7, 176 /*0xB0*/);
    this.ui_auto_start_label1.Name = "ui_auto_start_label1";
    this.ui_auto_start_label1.Size = new Size(236, 25);
    this.ui_auto_start_label1.TabIndex = 9;
    this.ui_auto_start_label1.Text = "Auto-start with Windows";
    this.ui_auto_start_label1.TextAlign = ContentAlignment.MiddleLeft;
    this.ui_auto_start_checkbox.AutoSize = true;
    this.ui_auto_start_checkbox.Location = new Point(244, 180);
    this.ui_auto_start_checkbox.Name = "ui_auto_start_checkbox";
    this.ui_auto_start_checkbox.Size = new Size(15, 14);
    this.ui_auto_start_checkbox.TabIndex = 11;
    this.ui_auto_start_checkbox.UseVisualStyleBackColor = true;
    this.ui_auto_start_checkbox.Click += new EventHandler(this.ui_auto_start_click);
    this.imageList1.ImageStream = (ImageListStreamer) componentResourceManager.GetObject("imageList1.ImageStream");
    this.imageList1.TransparentColor = System.Drawing.Color.Transparent;
    this.imageList1.Images.SetKeyName(0, "home.png");
    this.imageList1.Images.SetKeyName(1, "settings.png");
    this.imageList1.Images.SetKeyName(2, "home_small.png");
    this.imageList1.Images.SetKeyName(3, "settings_small.png");
    this.AutoScaleMode = AutoScaleMode.None;
    this.BackColor = System.Drawing.Color.LightCyan;
    this.Controls.Add((Control) this.tabControl1);
    this.Font = new Font("Segoe UI", 9f);
    this.Margin = new Padding(3, 2, 3, 2);
    this.Name = nameof (NB21Logger);
    this.Size = new Size(594, 236);
    this.Load += new EventHandler(this.Form1_Load);
    this.tabControl1.ResumeLayout(false);
    this.tabPage_Home.ResumeLayout(false);
    this.tabPage_Home.PerformLayout();
    ((ISupportInitialize) this.ui_file_icon).EndInit();
    ((ISupportInitialize) this.pictureBox_statusImage).EndInit();
    this.tabPage_Settings.ResumeLayout(false);
    this.tabPage_Settings.PerformLayout();
    this.ResumeLayout(false);
  }
}
